install.packages("XML", repos="https://ftp.acc.umu.se/mirror/CRAN/")
install.packages("rmarkdown", repos="https://ftp.acc.umu.se/mirror/CRAN/")
install.packages("data.table", dependencies=TRUE, repos="https://ftp.acc.umu.se/mirror/CRAN/")
install.packages("ggplot2", repos="https://ftp.acc.umu.se/mirror/CRAN/")
install.packages("dplyr", repos="https://ftp.acc.umu.se/mirror/CRAN/")
install.packages("ggrepel", repos="https://ftp.acc.umu.se/mirror/CRAN/")
install.packages("VennDiagram", repos="https://ftp.acc.umu.se/mirror/CRAN/")
install.packages("htmlTable", repos="https://ftp.acc.umu.se/mirror/CRAN/")
install.packages("kableExtra", repos="https://ftp.acc.umu.se/mirror/CRAN/")
install.packages("tictoc", repos="https://ftp.acc.umu.se/mirror/CRAN/")
install.packages("optparse", repos="https://ftp.acc.umu.se/mirror/CRAN/")
source("https://bioconductor.org/biocLite.R")
biocLite("VariantAnnotation")
